# Generated by Django 2.2.4 on 2019-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0002_project_projecttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Tecnology', 'Information Tecnology'), ('Software Engineering', 'Software Engineering'), ('Cyber Security', 'Cyber Security')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.CharField(choices=[('Research Work', 'Research Work'), ('Design and Implementation', 'Design and Implementation')], max_length=100),
        ),
    ]
