# Generated by Django 3.2.5 on 2021-08-02 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alloc', '0005_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('doctor_feedback', models.TextField()),
                ('doctor_comment', models.TextField()),
                ('doctor', models.CharField(choices=[('sule', 'Dr Mathew Sule - Dentist'), ('isa', 'Dr Abubakar Isa - Surgeon'), ('zaharadden', 'Dr zaharadden - Opthalmologist'), ('kareem', 'Dr Abdulkareem - Cardiologist'), ('lawan', 'Dr Abba Lawan - Endocrinologist'), ('kano', 'Isa Kano - Gynecologist')], max_length=100)),
                ('date', models.DateTimeField(max_length=100)),
                ('status', models.CharField(choices=[('Review', 'Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=100)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
