# Generated by Django 3.2.5 on 2021-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0006_auto_20210802_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='choose_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_attended_to',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Appointment under Review', 'Appointment under Review'), ('Appointment Accepted', 'Appointment Accepted'), ('Appointment Rejected', 'Appointment Rejected')], max_length=100),
        ),
    ]
