# Generated by Django 3.2.5 on 2021-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0007_auto_20210802_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
